export const ADD_PRODUCT_TO_CART = 'cart/ADD_PRODUCT_TO_CART';
export const INCREASE_PRODUCT = 'cart/INCREASE_PRODUCT';
export const DECREASE_PRODUCT = 'cart/DECREASE_PRODUCT';
export const REMOVE_PRODUCT = 'cart/REMOVE_PRODUCT';